global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using WebAPI.Controllers;
global using WebAPI.Data;
global using WebAPI.DTOs;
global using WebAPI.Handlers;
global using WebAPI.Interfaces;
global using WebAPI.Models;